// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBoGNo78YLtjF1Ep7Tc942Zx80v5h4vC0',
    appId: '1:713457170325:web:dbc7c47416d256d5f2289c',
    messagingSenderId: '713457170325',
    projectId: 'stocktrackerapp-919cd',
    authDomain: 'stocktrackerapp-919cd.firebaseapp.com',
    storageBucket: 'stocktrackerapp-919cd.firebasestorage.app',
    measurementId: 'G-78KZ32X16P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEpoojirmWXXCvUc0B6TssG_QNagIq3iA',
    appId: '1:713457170325:android:fc5c029f8cf9b661f2289c',
    messagingSenderId: '713457170325',
    projectId: 'stocktrackerapp-919cd',
    storageBucket: 'stocktrackerapp-919cd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1U7WruB-sLrPwnIK4yp5YQ_QzzrwlybY',
    appId: '1:713457170325:ios:185ff70130719edaf2289c',
    messagingSenderId: '713457170325',
    projectId: 'stocktrackerapp-919cd',
    storageBucket: 'stocktrackerapp-919cd.firebasestorage.app',
    iosBundleId: 'com.example.stocktrackerapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1U7WruB-sLrPwnIK4yp5YQ_QzzrwlybY',
    appId: '1:713457170325:ios:185ff70130719edaf2289c',
    messagingSenderId: '713457170325',
    projectId: 'stocktrackerapp-919cd',
    storageBucket: 'stocktrackerapp-919cd.firebasestorage.app',
    iosBundleId: 'com.example.stocktrackerapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBoGNo78YLtjF1Ep7Tc942Zx80v5h4vC0',
    appId: '1:713457170325:web:4e75810673dd2fb4f2289c',
    messagingSenderId: '713457170325',
    projectId: 'stocktrackerapp-919cd',
    authDomain: 'stocktrackerapp-919cd.firebaseapp.com',
    storageBucket: 'stocktrackerapp-919cd.firebasestorage.app',
    measurementId: 'G-0GQF4E5WMJ',
  );
}
